#!/usr/bin/env bash

################################################################################
# Fills a file with lines consisting of the specified characters, each line
# consisting of one character. A block of such lines can be repeated several times

OUTPUT_FILE="${1}"
LINE_LENGTH="${2:-80}"
BLOCK_REPETITIONS="${3:-1}"
CHARACTERS="${4:-* 0 1 2 3 4 5 6 7 8 9}"

################################################################################

set -o errexit
set -o nounset
set -o pipefail
set -o noglob

block=""

for char in ${CHARACTERS}; do
    line=""

    # An expression with zero value of variable returns a non-zero exit code
    ((length = 0)) || true

    while test "${length}" -lt "${LINE_LENGTH}"; do
        line+="${char}"

        ((length++)) || true
    done

    block+="${line}"$'\n'
done

# Preventing a non-zero exit code from being returned by excluding the zero
# value of a variable
((repeat = 1))

while test "${repeat}" -le "${BLOCK_REPETITIONS}"; do
    printf -- '%s' "${block}"

    ((repeat++))
done >>"${OUTPUT_FILE}"
