#!/usr/bin/env bash

################################################################################
# Demonstrates tracking for unexpected termination of child processes

PROTOCOL='socks'
CREDENTIALS='user:password'
PORT='8080'

################################################################################

set -o errexit
set -o nounset
set -o pipefail
set -o noglob

trap 'cleanup 2>/dev/null' EXIT
trap 'graceful' SIGTERM SIGINT

cleanup() {
    set +o errexit
    set +o nounset
    set +o pipefail

    for job in $(jobs -p); do
        kill "${job}"
    done

    wait

    test -n "${IS_GRACEFUL_TERMINATION}" && exit 0

    exit 1
}

graceful() {
    IS_GRACEFUL_TERMINATION=true
}

ADDRS="$(bash -c "ip -json addr | jq -r '.[] | .addr_info[] | select(.family==\"inet\") | .local'")"

for addr in ${ADDRS}; do
    bash -c "gost -L '${PROTOCOL}://${CREDENTIALS}@${addr}:${PORT}'" &
done

wait -n
