#!/usr/bin/env bash

################################################################################
# Demonstrates tracking for unexpected termination of child processes

PROTOCOL='socks'
CREDENTIALS='user:password'
PORT='8080'

################################################################################

set -o errexit
set -o nounset
set -o pipefail
set -o noglob

trap 'cleanup 2>/dev/null' EXIT
trap 'graceful' SIGTERM SIGINT

function cleanup() {
    set +o errexit
    set +o nounset
    set +o pipefail

    for job in $(jobs -p); do
        kill -- "${job}"
    done

    wait

    # A signal handler is executed in the same process that called it
    test -n "${IS_GRACEFUL_TERMINATION}" && exit 0

    exit 1
}

function graceful() {
    IS_GRACEFUL_TERMINATION='yes'
}

ADDRS="$(bash -c "ip -json addr | jq -r '.[] | .addr_info[] | select(.family==\"inet\") | .local'")"

for addr in ${ADDRS}; do
    bash -c "gost -L '${PROTOCOL}://${CREDENTIALS}@${addr}:${PORT}'" &
done

wait -n
