name: Bash
on:
  push:
  pull_request:
permissions:
  contents: read
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: find . -type f -executable -not -path './.git/*' -print -exec shellcheck {} +
